import type { Metadata } from "next";
import { Roboto , Cairo} from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import ReduxProvider from "@/providers/ReduxProvider";


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
       <ReduxProvider>
       <div className="flex flex-col min-h-screen" >
          <Header />
          <main className="flex-1" >
          {children}
          </main>
        </div>
       </ReduxProvider>
      </body>
    </html>
  );
}
